###
GET {{buttfly}}/activity/find-today-fly
Content-Type: application/json
X-Token: {{auth_token}}

{}

###
POST {{buttfly}}/activity/new-daily-fly
Content-Type: application/json
X-Token: {{auth_token}}

{
  "theme": "灯",
  "flyRule": "Common",
  "date": "20240504",
  "background": "https://pic-artastic.oss-cn-shanghai.aliyuncs.com/flower/534de8d0631b5d093da7e878e90e279b.png"
}

###
GET {{buttfly}}/file/find-default-fly-arena-covers
Content-Type: application/json
X-Token: {{auth_token}}
