###
GET {{buttfly}}/fly-arena/find-taken-part
Content-Type: application/json
X-Token: {{auth_token}}

{}

###
GET {{buttfly}}/fly-arena/find-by-take-part-mode?mode=Open
Content-Type: application/json
X-Token: {{auth_token}}

{}

###
POST {{buttfly}}/fly-arena/new
Content-Type: application/json
X-Token: {{auth_token}}

{
  "theme": "春",
  "flyRule": "Common",
  "mode": "Internal",
  "background": "https://img.cjyun.org.cn/a/10008/201805/90a8a8e76ab9de005e34f0778367ae22.jpeg"
}

> {% client.global.set('last_fly_arena_id', response.body.data.id); %}

###
POST {{buttfly}}/fly-arena/new
Content-Type: application/json
X-Token: {{auth_token}}

{
  "theme": "夏",
  "flyRule": "Common",
  "mode": "Open",
  "background": "https://img.cjyun.org.cn/a/10008/201805/90a8a8e76ab9de005e34f0778367ae22.jpeg"
}

> {% client.global.set('last_fly_arena_id', response.body.data.id); %}

###
POST {{buttfly}}/fly-arena/fly
Content-Type: application/json
X-Token: {{auth_token}}

{
  "flyArenaId": {{last_fly_arena_id}},
  "pollen": "春城无处不飞花",
  "title": "",
  "author": ""
}

> {% client.global.set('last_fly_arena_id', response.body.data.id); %}

###
POST {{buttfly}}/fly-arena/fly
Content-Type: application/json
X-Token: {{auth_token}}

{
  "flyArenaId": {{last_fly_arena_id}},
  "pollen": "想眼中能有多少泪珠儿，\n怎禁得秋流到冬尽，\n春流到夏!",
  "title": "",
  "author": ""
}

> {% client.global.set('last_fly_arena_id', response.body.data.id); %}

###
POST {{buttfly}}/fly-arena/fly
Content-Type: application/json
X-Token: {{auth_token}}

{
  "flyArenaId": {{last_fly_arena_id}},
  "pollen": "想眼中能有多少泪珠儿，\n怎禁得秋流到冬尽，\n春流到夏! 春流到夏!春流到夏!",
  "title": "曹雪芹《红楼梦十二曲·其三·枉凝眉》",
  "author": ""
}

> {% client.global.set('last_fly_arena_id', response.body.data.id); %}
