###
POST {{buttfly}}/s/register-from-wechat-and-sign-in
Content-Type: application/json

{
  "openId": "testopenid",
  "nickname": "xjl",
  "avatar": "https://i.pinimg.com/236x/ae/f3/35/aef3359d6d36e4042a2f9f0c2027a048.jpg"
}

> {% client.global.set('auth_token', response.body.data.token.id); %}

###
POST {{buttfly}}/s/d-sign-in
Content-Type: application/json

{
  "channelId": "testopenid",
  "channel": "Wechat"
}

> {% client.global.set('auth_token', response.body.data.token.id); %}

###
OPTIONS https://wormhole.dcyy.cc/butterfly/s/d-sign-in
accept: */*
access-control-request-method: POST
access-control-request-headers: content-type
origin: http://192.168.3.24:10086
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36
sec-fetch-mode: cors
sec-fetch-site: cross-site
sec-fetch-dest: empty
referer: http://192.168.3.24:10086/
accept-encoding: gzip, deflate, br, zstd
accept-language: zh-CN,zh;q=0.9

{
  "channelId": "testopenid",
  "channel": "Wechat"
}
